### ISSUE TITLE
once method is not working

### ISSUE THREAD

**Issue by jeromevalentin** [RangerMauve/mqtt-emitter#3]
Edit: Fixed in 1.2.1 ...! Sorry

Edit: Duplicate of #1 ... but still open on version 1.2.0

Using the emitter.once(topic, handler) method, lead to an error: 
--> no removeListener function defined on undefined.

Extracted from index.js
/**
- Adds a one time listener for the event
- @param  {String}      topic   Topic pattern to listen on
- @param  {Function}    handler Function to call the next time this topic appears
- @return {MQTTEmitter}         Returns self for use in chaining
  */
  function once(topic, handler) {
  once_handler.handler = handler;
  this.on(topic, once_handler);
  
  return this;
  
  function once_handler(data, params) {
      handler.call(this, data, params);
  **// HERE this does not refer the right object, leading to the error.
      this.removeListener(topic, once_handler);**
  }
  }

**Comment by RangerMauve** [comment]
Did you try 1.2.1?

**Comment by RangerMauve** [comment]
Just read the edit. NP. :P
